import functools
import json
from datetime import date

from flask import Blueprint, Response, jsonify, request, session
from werkzeug.security import check_password_hash, generate_password_hash

from ..database import get_connection, log_audit
from ..services.application_service import update_status

staff_bp = Blueprint("staff", __name__)


def _daily_report_pdf(report_date, totals, rows):
    lines = [
        "MUNICIPALITY OF CATARMAN",
        "eSHCAT DAILY COMMUNITY REPORT",
        f"Report date: {report_date}",
        "",
        f"Total reports: {totals['total']}",
        f"Open: {totals['Open']}",
        f"In Progress: {totals['In Progress']}",
        f"Resolved: {totals['Resolved']}",
        "",
        "Reports received today",
    ]
    for row in rows:
        lines.append(f"{row['reference_number']} | {row['category']} | {row['status']}")
        lines.append(f"Location: {row['location'] or '—'}")
        lines.append(f"Description: {row['description'] or '—'}")
        lines.append("")
    if not rows:
        lines.append("No community reports were submitted today.")
    lines.extend(["", "Generated by eSHCAT · Electronic Services Hub of Catarman"])
    pages = [lines[i:i + 42] for i in range(0, len(lines), 42)] or [[]]
    objects = [None, None, b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"]
    page_ids = []
    for page_lines in pages:
        commands = ["BT", "/F1 9 Tf", "50 750 Td", "13 TL"]
        for index, line in enumerate(page_lines):
            safe = line.encode("latin-1", "replace").decode("latin-1")
            escaped = safe.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
            commands.append(f"({escaped}) Tj")
            if index < len(page_lines) - 1:
                commands.append("T*")
        commands.append("ET")
        content = "\n".join(commands).encode("latin-1")
        content_id = len(objects) + 1
        objects.append(f"<< /Length {len(content)} >>\nstream\n".encode("latin-1") + content + b"\nendstream")
        page_id = len(objects) + 1
        objects.append(None)
        page_ids.append((page_id, content_id))
    objects[0] = b"<< /Type /Catalog /Pages 2 0 R >>"
    objects[1] = f"<< /Type /Pages /Kids [{' '.join(f'{page_id} 0 R' for page_id, _ in page_ids)}] /Count {len(page_ids)} >>".encode("latin-1")
    for page_id, content_id in page_ids:
        objects[page_id - 1] = f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents {content_id} 0 R >>".encode("latin-1")
    pdf = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for object_id, obj in enumerate(objects, 1):
        offsets.append(len(pdf))
        pdf.extend(f"{object_id} 0 obj\n".encode("latin-1")); pdf.extend(obj); pdf.extend(b"\nendobj\n")
    xref = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n".encode("latin-1"))
    for offset in offsets[1:]: pdf.extend(f"{offset:010d} 00000 n \n".encode("latin-1"))
    pdf.extend(f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode("latin-1"))
    return bytes(pdf)


def login_required(view):
    @functools.wraps(view)
    def wrapped(*args, **kwargs):
        if session.get("staff_id") is None:
            return jsonify({"error": "Authentication required."}), 401
        return view(*args, **kwargs)

    return wrapped


def admin_required(view):
    @functools.wraps(view)
    @login_required
    def wrapped(*args, **kwargs):
        if session.get("staff_role") != "Administrator":
            return jsonify({"error": "Administrator access required."}), 403
        return view(*args, **kwargs)

    return wrapped


def _department_filter():
    """Return the requested department for administrators, or force staff scope."""
    if session.get("staff_role") == "Administrator":
        return request.args.get("department_id", type=int)
    return session.get("department_id") or -1


def _department_allowed(department_id):
    return session.get("staff_role") == "Administrator" or department_id == session.get("department_id")


@staff_bp.post("/api/staff/login")
def login():
    payload = request.get_json(silent=True) or {}
    email = (payload.get("email") or "").strip().lower()
    password = payload.get("password") or ""

    conn = get_connection()
    try:
        user = conn.execute(
            "SELECT * FROM staff_users WHERE email = ? AND is_active = 1", (email,)
        ).fetchone()
        if user is None or not check_password_hash(user["password_hash"], password):
            return jsonify({"error": "Invalid email or password."}), 401

        session.clear()
        session["staff_id"] = user["id"]
        session["staff_name"] = user["name"]
        session["staff_role"] = user["role"]
        session["department_id"] = user["department_id"]
        session.permanent = True

        log_audit(conn, user["id"], "LOGIN", "staff", user["id"])
        conn.commit()
        return jsonify(
            {
                "id": user["id"],
                "name": user["name"],
                "email": user["email"],
                "role": user["role"],
                "department_id": user["department_id"],
            }
        )
    finally:
        conn.close()


@staff_bp.post("/api/staff/logout")
@login_required
def logout():
    conn = get_connection()
    try:
        log_audit(conn, session["staff_id"], "LOGOUT", "staff", session["staff_id"])
        conn.commit()
    finally:
        conn.close()
    session.clear()
    return jsonify({"message": "Logged out."})


@staff_bp.get("/api/staff/me")
@login_required
def me():
    return jsonify(
        {
            "id": session["staff_id"],
            "name": session["staff_name"],
            "role": session["staff_role"],
            "department_id": session["department_id"],
        }
    )


@staff_bp.get("/api/staff/users")
@admin_required
def list_staff_users():
    conn = get_connection()
    try:
        department_filter = request.args.get("department_id", type=int)
        where = " WHERE u.department_id = ?" if department_filter else ""
        params = (department_filter,) if department_filter else ()
        rows = conn.execute(
            """
            SELECT u.id, u.name, u.email, u.role, u.department_id, u.is_active,
                   d.name AS department_name
            FROM staff_users u
            LEFT JOIN departments d ON d.id = u.department_id
            """ + where + " ORDER BY u.name ASC",
            params,
        ).fetchall()
        return jsonify([dict(row) for row in rows])
    finally:
        conn.close()


@staff_bp.get("/api/staff/departments")
@admin_required
def list_staff_departments():
    conn = get_connection()
    try:
        rows = conn.execute(
            """
            SELECT id, name, description, location, contact_number, email, office_hours
            FROM departments ORDER BY name ASC
            """
        ).fetchall()
        departments = []
        for row in rows:
            department = dict(row)
            department["services"] = [
                dict(service)
                for service in conn.execute(
                    "SELECT id, name, estimated_processing FROM services WHERE department_id = ? ORDER BY name",
                    (row["id"],),
                ).fetchall()
            ]
            departments.append(department)
        return jsonify(departments)
    finally:
        conn.close()


@staff_bp.post("/api/staff/departments")
@admin_required
def create_department():
    payload = request.get_json(silent=True) or {}
    name = (payload.get("name") or "").strip()
    description = (payload.get("description") or "").strip()
    location = (payload.get("location") or "").strip()
    contact_number = (payload.get("contact_number") or "").strip()
    email = (payload.get("email") or "").strip()
    office_hours = (payload.get("office_hours") or "").strip()
    if not name:
        return jsonify({"error": "Office name is required."}), 400

    conn = get_connection()
    try:
        cursor = conn.execute(
            """
            INSERT INTO departments
                (name, description, location, contact_number, email, office_hours)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (name, description, location, contact_number, email, office_hours),
        )
        log_audit(conn, session["staff_id"], "CREATE_DEPARTMENT", "department", cursor.lastrowid, name)
        conn.commit()
        return jsonify({"message": "Office created.", "id": cursor.lastrowid}), 201
    finally:
        conn.close()


@staff_bp.patch("/api/staff/services/<int:service_id>")
@admin_required
def update_service_admin(service_id):
    payload = request.get_json(silent=True) or {}
    estimated_processing = (payload.get("estimated_processing") or "").strip()
    conn = get_connection()
    try:
        current = conn.execute("SELECT name FROM services WHERE id = ?", (service_id,)).fetchone()
        if current is None:
            return jsonify({"error": "Service not found."}), 404
        conn.execute(
            "UPDATE services SET estimated_processing = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
            (estimated_processing, service_id),
        )
        log_audit(conn, session["staff_id"], "UPDATE_SERVICE_PROCESSING", "service", service_id, current["name"])
        conn.commit()
        return jsonify({"message": "Processing time updated."})
    finally:
        conn.close()


@staff_bp.patch("/api/staff/departments/<int:department_id>")
@admin_required
def update_department(department_id):
    payload = request.get_json(silent=True) or {}
    name = (payload.get("name") or "").strip()
    description = (payload.get("description") or "").strip()
    location = (payload.get("location") or "").strip()
    contact_number = (payload.get("contact_number") or "").strip()
    email = (payload.get("email") or "").strip()
    office_hours = (payload.get("office_hours") or "").strip()
    if not name:
        return jsonify({"error": "Office name is required."}), 400

    conn = get_connection()
    try:
        current = conn.execute("SELECT id FROM departments WHERE id = ?", (department_id,)).fetchone()
        if current is None:
            return jsonify({"error": "Office not found."}), 404
        conn.execute(
            """
            UPDATE departments
            SET name = ?, description = ?, location = ?, contact_number = ?,
                email = ?, office_hours = ?
            WHERE id = ?
            """,
            (name, description, location, contact_number, email, office_hours, department_id),
        )
        log_audit(conn, session["staff_id"], "UPDATE_DEPARTMENT", "department", department_id, name)
        conn.commit()
        return jsonify({"message": "Office updated."})
    finally:
        conn.close()


@staff_bp.delete("/api/staff/departments/<int:department_id>")
@admin_required
def delete_department(department_id):
    conn = get_connection()
    try:
        current = conn.execute("SELECT name FROM departments WHERE id = ?", (department_id,)).fetchone()
        if current is None:
            return jsonify({"error": "Office not found."}), 404
        linked = {
            "services": conn.execute("SELECT COUNT(*) AS c FROM services WHERE department_id = ?", (department_id,)).fetchone()["c"],
            "staff": conn.execute("SELECT COUNT(*) AS c FROM staff_users WHERE department_id = ?", (department_id,)).fetchone()["c"],
            "applications": conn.execute("SELECT COUNT(*) AS c FROM applications WHERE department_id = ?", (department_id,)).fetchone()["c"],
            "appointments": conn.execute("SELECT COUNT(*) AS c FROM appointments WHERE department_id = ?", (department_id,)).fetchone()["c"],
            "reports": conn.execute("SELECT COUNT(*) AS c FROM community_reports WHERE department_id = ?", (department_id,)).fetchone()["c"],
        }
        if any(linked.values()):
            return jsonify({"error": "This office cannot be deleted while it has linked services, staff, or records."}), 409
        conn.execute("DELETE FROM departments WHERE id = ?", (department_id,))
        log_audit(conn, session["staff_id"], "DELETE_DEPARTMENT", "department", department_id, current["name"])
        conn.commit()
        return jsonify({"message": "Office deleted."})
    finally:
        conn.close()


@staff_bp.post("/api/staff/users")
@admin_required
def create_staff_user():
    payload = request.get_json(silent=True) or {}
    name = (payload.get("name") or "").strip()
    email = (payload.get("email") or "").strip().lower()
    password = payload.get("password") or ""
    role = (payload.get("role") or "Staff").strip()
    department_id = payload.get("department_id") or None
    if not name or not email or len(password) < 6:
        return jsonify({"error": "Name, email, and a password of at least 6 characters are required."}), 400
    if role not in ("Staff", "Department Head", "Administrator", "Auditor"):
        return jsonify({"error": "Invalid staff role."}), 400

    conn = get_connection()
    try:
        if conn.execute("SELECT id FROM staff_users WHERE email = ?", (email,)).fetchone():
            return jsonify({"error": "A staff account with this email already exists."}), 409
        cursor = conn.execute(
            """
            INSERT INTO staff_users (name, email, password_hash, role, department_id, is_active)
            VALUES (?, ?, ?, ?, ?, 1)
            """,
            (name, email, generate_password_hash(password), role, department_id),
        )
        log_audit(conn, session["staff_id"], "CREATE_STAFF", "staff", cursor.lastrowid, email)
        conn.commit()
        return jsonify({"message": "Staff account created.", "id": cursor.lastrowid}), 201
    finally:
        conn.close()


@staff_bp.patch("/api/staff/users/<int:user_id>")
@admin_required
def update_staff_user(user_id):
    payload = request.get_json(silent=True) or {}
    name = (payload.get("name") or "").strip()
    email = (payload.get("email") or "").strip().lower()
    role = (payload.get("role") or "Staff").strip()
    department_id = payload.get("department_id") or None
    is_active = 1 if payload.get("is_active", True) else 0
    password = payload.get("password") or ""
    if not name or not email:
        return jsonify({"error": "Name and email are required."}), 400
    if role not in ("Staff", "Department Head", "Administrator", "Auditor"):
        return jsonify({"error": "Invalid staff role."}), 400
    if user_id == session.get("staff_id") and not is_active:
        return jsonify({"error": "You cannot deactivate your own account."}), 400

    conn = get_connection()
    try:
        current = conn.execute("SELECT id FROM staff_users WHERE id = ?", (user_id,)).fetchone()
        if current is None:
            return jsonify({"error": "Staff account not found."}), 404
        duplicate = conn.execute(
            "SELECT id FROM staff_users WHERE email = ? AND id <> ?", (email, user_id)
        ).fetchone()
        if duplicate:
            return jsonify({"error": "A staff account with this email already exists."}), 409
        if password:
            conn.execute(
                """
                UPDATE staff_users SET name = ?, email = ?, password_hash = ?, role = ?,
                    department_id = ?, is_active = ? WHERE id = ?
                """,
                (name, email, generate_password_hash(password), role, department_id, is_active, user_id),
            )
        else:
            conn.execute(
                """
                UPDATE staff_users SET name = ?, email = ?, role = ?, department_id = ?,
                    is_active = ? WHERE id = ?
                """,
                (name, email, role, department_id, is_active, user_id),
            )
        log_audit(conn, session["staff_id"], "UPDATE_STAFF", "staff", user_id, email)
        conn.commit()
        return jsonify({"message": "Staff account updated."})
    finally:
        conn.close()


@staff_bp.get("/api/staff/dashboard")
@login_required
def dashboard():
    conn = get_connection()
    try:
        department_id = _department_filter()

        def count_by(table, condition="", params=()):
            sql = f"SELECT COUNT(*) c FROM {table}"
            query_params = list(params)
            if condition:
                sql += " WHERE " + condition
            if department_id:
                sql += " AND department_id = ?" if condition else " WHERE department_id = ?"
                query_params.append(department_id)
            return conn.execute(sql, query_params).fetchone()["c"]

        stats = {
            "total": count_by("applications"),
            "today": count_by("applications", "DATE(created_at) = CURRENT_DATE"),
            "Pending": count_by("applications", "status = 'Submitted'"),
            "Received": count_by("applications", "status = 'Received'"),
            "Under Review": count_by("applications", "status = 'Under Review'"),
            "Approved": count_by("applications", "status = 'Approved'"),
            "Rejected": count_by("applications", "status = 'Rejected'"),
            "Completed": count_by("applications", "status = 'Completed'"),
            "appointments": count_by("appointments", "status = 'Pending'"),
            "reports": count_by("community_reports", "status = 'Open'"),
        }
        return jsonify(stats)
    finally:
        conn.close()


@staff_bp.get("/api/staff/applications")
@login_required
def list_applications():
    conn = get_connection()
    try:
        status_filter = request.args.get("status")
        department_filter = _department_filter()
        sql = """
            SELECT a.id, a.reference_number, a.full_name, a.status, a.created_at,
                   s.name AS service_name, d.name AS department_name
            FROM applications a
            JOIN services s ON s.id = a.service_id
            JOIN departments d ON d.id = a.department_id
        """
        params = []
        filters = []
        if status_filter:
            filters.append("a.status = ?")
            params.append(status_filter)
        if department_filter is not None:
            filters.append("a.department_id = ?")
            params.append(department_filter)
        if filters:
            sql += " WHERE " + " AND ".join(filters)
        sql += " ORDER BY a.created_at DESC"
        rows = conn.execute(sql, params).fetchall()
        return jsonify([dict(r) for r in rows])
    finally:
        conn.close()


@staff_bp.get("/api/staff/appointments")
@login_required
def list_appointments():
    conn = get_connection()
    try:
        department_filter = _department_filter()
        sql = """
            SELECT a.*, s.name AS service_name, d.name AS department_name
            FROM appointments a
            LEFT JOIN services s ON s.id = a.service_id
            LEFT JOIN departments d ON d.id = a.department_id
        """
        params = []
        if department_filter is not None:
            sql += " WHERE a.department_id = ?"
            params.append(department_filter)
        sql += " ORDER BY a.appointment_date ASC, a.appointment_time ASC, a.created_at DESC"
        rows = conn.execute(sql, params).fetchall()
        return jsonify([dict(r) for r in rows])
    finally:
        conn.close()


@staff_bp.get("/api/staff/reports")
@login_required
def list_reports():
    conn = get_connection()
    try:
        department_filter = _department_filter()
        sql = "SELECT * FROM community_reports"
        params = []
        if department_filter is not None:
            sql += " WHERE department_id = ?"
            params.append(department_filter)
        sql += " ORDER BY created_at DESC"
        rows = conn.execute(sql, params).fetchall()
        return jsonify([dict(r) for r in rows])
    finally:
        conn.close()


def _todays_reports(conn):
    department_id = session.get("department_id") if session.get("staff_role") != "Administrator" else None
    where = "DATE(created_at) = CURRENT_DATE"
    params = []
    if department_id:
        where += " AND department_id = ?"
        params.append(department_id)
    return conn.execute(
        f"SELECT reference_number, category, location, description, status FROM community_reports WHERE {where} ORDER BY created_at DESC",
        params,
    ).fetchall()


@staff_bp.get("/api/staff/reports/daily-summary")
@login_required
def daily_report_summary():
    conn = get_connection()
    try:
        rows = _todays_reports(conn)
        totals = {status: sum(1 for row in rows if row["status"] == status) for status in ("Open", "In Progress", "Resolved")}
        totals["total"] = len(rows)
        return jsonify({"date": date.today().isoformat(), "totals": totals})
    finally:
        conn.close()


@staff_bp.get("/api/staff/reports/daily.pdf")
@login_required
def download_daily_report():
    conn = get_connection()
    try:
        rows = _todays_reports(conn)
        totals = {status: sum(1 for row in rows if row["status"] == status) for status in ("Open", "In Progress", "Resolved")}
        totals["total"] = len(rows)
        pdf = _daily_report_pdf(date.today().isoformat(), totals, rows)
        return Response(pdf, mimetype="application/pdf", headers={"Content-Disposition": "attachment; filename=eshcat-daily-reports.pdf"})
    finally:
        conn.close()


@staff_bp.get("/api/staff/messages")
@login_required
def list_messages():
    conn = get_connection()
    try:
        rows = conn.execute(
            """
            SELECT n.*, a.reference_number
            FROM notifications n
            LEFT JOIN applications a ON a.id = n.application_id
            ORDER BY n.created_at DESC
            """
        ).fetchall()
        return jsonify([dict(r) for r in rows])
    finally:
        conn.close()


@staff_bp.get("/api/staff/activity")
@login_required
def list_activity():
    page = max(request.args.get("page", 1, type=int), 1)
    per_page = 10
    offset = (page - 1) * per_page
    conn = get_connection()
    try:
        total = conn.execute("SELECT COUNT(*) AS c FROM audit_logs").fetchone()["c"]
        rows = conn.execute(
            """
            SELECT l.id, l.action, l.entity_type, l.entity_id, l.details, l.created_at,
                   u.name AS staff_name
            FROM audit_logs l
            LEFT JOIN staff_users u ON u.id = l.staff_id
            ORDER BY l.created_at DESC, l.id DESC
            LIMIT ? OFFSET ?
            """,
            (per_page, offset),
        ).fetchall()
        return jsonify({"items": [dict(row) for row in rows], "page": page, "per_page": per_page, "total": total, "pages": max((total + per_page - 1) // per_page, 1)})
    finally:
        conn.close()


@staff_bp.get("/api/staff/applications/<int:app_id>")
@login_required
def get_application(app_id):
    conn = get_connection()
    try:
        row = conn.execute(
            """
            SELECT a.*, s.name AS service_name, s.estimated_processing, d.name AS department_name
            FROM applications a
            JOIN services s ON s.id = a.service_id
            JOIN departments d ON d.id = a.department_id
            WHERE a.id = ?
            """,
            (app_id,),
        ).fetchone()
        if row is None:
            return jsonify({"error": "Application not found."}), 404
        if not _department_allowed(row["department_id"]):
            return jsonify({"error": "This application belongs to another department."}), 403
        history = conn.execute(
            """
            SELECT h.*, su.name AS staff_name
            FROM application_history h
            LEFT JOIN staff_users su ON su.id = h.staff_id
            WHERE h.application_id = ?
            ORDER BY h.created_at DESC
            """,
            (app_id,),
        ).fetchall()
        result = dict(row)
        result["form_data"] = json.loads(row["form_data"] or "{}")
        result["history"] = [dict(h) for h in history]
        log_audit(conn, session["staff_id"], "VIEW_APPLICATION", "application", app_id)
        conn.commit()
        return jsonify(result)
    finally:
        conn.close()


@staff_bp.patch("/api/staff/applications/<int:app_id>/status")
@login_required
def patch_status(app_id):
    payload = request.get_json(silent=True) or {}
    new_status = payload.get("status")
    remarks = payload.get("remarks") or ""
    conn = get_connection()
    try:
        row = conn.execute("SELECT department_id FROM applications WHERE id = ?", (app_id,)).fetchone()
    finally:
        conn.close()
    if row is None:
        return jsonify({"error": "Application not found."}), 404
    if not _department_allowed(row["department_id"]):
        return jsonify({"error": "This application belongs to another department."}), 403
    try:
        result = update_status(app_id, session["staff_id"], new_status, remarks)
    except ValueError as exc:
        return jsonify({"error": str(exc)}), 400
    if result is False:
        return jsonify({"error": "Application not found."}), 404
    if not result["changed"]:
        return jsonify({"error": f"Application is already {result['status']}. No status change was made."}), 409
    conn = get_connection()
    try:
        log_audit(conn, session["staff_id"], "UPDATE_STATUS", "application", app_id, new_status)
        conn.commit()
    finally:
        conn.close()
    return jsonify({"message": "Status updated.", "status": new_status, "changed": True})


@staff_bp.post("/api/staff/applications/<int:app_id>/forward")
@login_required
def forward_application(app_id):
    payload = request.get_json(silent=True) or {}
    department_id = payload.get("department_id")
    remarks = payload.get("remarks") or ""
    if not department_id:
        return jsonify({"error": "Destination department is required."}), 400
    conn = get_connection()
    try:
        row = conn.execute("SELECT id, department_id FROM applications WHERE id = ?", (app_id,)).fetchone()
        if row is None:
            return jsonify({"error": "Application not found."}), 404
        if not _department_allowed(row["department_id"]):
            return jsonify({"error": "This application belongs to another department."}), 403
        current = conn.execute(
            "SELECT status FROM applications WHERE id = ?", (app_id,)
        ).fetchone()["status"]
        conn.execute(
            "UPDATE applications SET department_id = ?, status = 'Forwarded', updated_at = CURRENT_TIMESTAMP WHERE id = ?",
            (department_id, app_id),
        )
        conn.execute(
            "INSERT INTO application_history (application_id, staff_id, old_status, new_status, remarks) "
            "VALUES (?, ?, ?, 'Forwarded', ?)",
            (app_id, session["staff_id"], current, remarks or f"Forwarded to department {department_id}"),
        )
        log_audit(
            conn, session["staff_id"], "FORWARD_APPLICATION", "application", app_id,
            f"to department {department_id}",
        )
        conn.commit()
        return jsonify({"message": "Application forwarded."})
    finally:
        conn.close()
